// Command notices prints THIRD_PARTY_NOTICES: the licence and NOTICE files of
// every Go module linked into the three release binaries, then the licences of
// the embedded tree-sitter WebAssembly builds. The committed file at the
// repository root must equal this output (see main_test.go); regenerate with
//
//	go run ./scripts/notices > THIRD_PARTY_NOTICES
package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const module = "github.com/dark-factory-build/dark-factory"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "notices:", err)
		os.Exit(1)
	}
}

func run() error {
	// The release targets are macOS only, so the dependency set is darwin's
	// wherever this runs.
	deps := exec.Command("go", "list", "-deps", "-f", "{{with .Module}}{{.Path}} {{.Version}} {{.Dir}}{{end}}",
		module+"/cmd/factoryd", module+"/cmd/factoryctl", module+"/cmd/factory-runner")
	deps.Env = append(os.Environ(), "GOOS=darwin", "GOARCH=arm64")
	list, err := deps.Output()
	if err != nil {
		return err
	}
	root, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}").Output()
	if err != nil {
		return err
	}
	grammars, err := os.ReadFile(filepath.Join(strings.TrimSpace(string(root)), "internal/opgraph/treesitter/wasm/LICENSES.txt"))
	if err != nil {
		return err
	}
	// Not every Go distribution ships GOROOT/LICENSE (Homebrew's does not).
	golang, err := os.ReadFile(filepath.Join(strings.TrimSpace(string(root)), "scripts/notices/GO_LICENSE"))
	if err != nil {
		return err
	}
	lines := strings.Split(strings.TrimSpace(string(list)), "\n")
	sort.Strings(lines)
	var out strings.Builder
	out.WriteString("Third-party notices for factoryd, factoryctl and factory-runner.\n" +
		"Generated by `go run ./scripts/notices`; do not edit.\n\n" +
		"Go modules linked into the binaries\n\n")
	var last string
	for _, line := range lines {
		path, rest, _ := strings.Cut(line, " ")
		version, dir, _ := strings.Cut(rest, " ")
		if path == module || line == last {
			continue
		}
		last = line
		files, _ := filepath.Glob(filepath.Join(dir, "*"))
		fmt.Fprintf(&out, "==== %s %s\n\n", path, version)
		for _, file := range files {
			if name := strings.ToUpper(filepath.Base(file)); strings.HasPrefix(name, "LICENSE") || strings.HasPrefix(name, "COPYING") || strings.HasPrefix(name, "NOTICE") {
				text, err := os.ReadFile(file)
				if err != nil {
					return err
				}
				fmt.Fprintf(&out, "-- %s\n\n%s\n", filepath.Base(file), text)
			}
		}
	}
	fmt.Fprintf(&out, "==== Go standard library and runtime\n\n-- LICENSE\n\n%s\n", golang)
	out.WriteString("Embedded tree-sitter WebAssembly builds (internal/opgraph/treesitter)\n\n")
	out.Write(grammars)
	_, err = os.Stdout.WriteString(strings.TrimRight(out.String(), "\n") + "\n")
	return err
}
